// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KoiCenter.WPF.Models;

[Table("CartItem")]
public partial class CartItem
{
    [Key]
    public int Id { get; set; }

    public int? CartId { get; set; }

    public int? ServiceId { get; set; }

    public int? ProductId { get; set; }

    public bool? IsDeleted { get; set; }

    public int? OrderHistoryId { get; set; }
}