// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KoiCenter.WPF.Models;

[Table("Feedback")]
public partial class Feedback
{
    [Key]
    public int Id { get; set; }

    public int? ServiceId { get; set; }

    public int? CustomerId { get; set; }

    [Column(TypeName = "decimal(3, 2)")]
    public decimal? Rating { get; set; }

    [Column(TypeName = "text")]
    public string FeedbackText { get; set; }
}