// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KoiCenter.WPF.Models;

[Table("OrderItem")]
public partial class OrderItem
{
    [Key]
    public int OrderItemId { get; set; }

    public int? OrderId { get; set; }

    public int? PetId { get; set; }

    public int? ServiceId { get; set; }

    public int? ProductId { get; set; }

    public int? VeterinarianId { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Price { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? TravelCost { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Location { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? AppointmentDateTime { get; set; }
}