// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KoiCenter.WPF.Models;

[Table("Pet")]
public partial class Pet
{
    [Key]
    public int Id { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Name { get; set; }

    public int? Age { get; set; }

    public int? PetTypeId { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Breed { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string ImageUrl { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Color { get; set; }

    public double? Length { get; set; }

    public double? Weight { get; set; }

    public int? Quantity { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastHealthCheck { get; set; }

    public int? OwnerId { get; set; }

    public int? HealthStatus { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string CreatedBy { get; set; }

    public bool? IsDeleted { get; set; }
}