// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KoiCenter.WPF.Models;

[Table("PetService")]
public partial class PetService
{
    [Key]
    public int Id { get; set; }

    public int? ServiceCategoryId { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? BasePrice { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Duration { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string ImageUrl { get; set; }

    public int? StaffQuantity { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? AvailableFrom { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? AvailableTo { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? TravelCost { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string CreatedBy { get; set; }

    public bool? IsDeleted { get; set; }
}