// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KoiCenter.WPF.Models;

[Table("PetType")]
public partial class PetType
{
    [Key]
    public int Id { get; set; }

    public int? EnvironmentId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string GeneralType { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string SpecificType { get; set; }
}