// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KoiCenter.WPF.Models;

[Table("User")]
[Index("Username", Name = "UQ__User__536C85E4D122F84E", IsUnique = true)]
[Index("Email", Name = "UQ__User__A9D10534CB00006F", IsUnique = true)]
public partial class User
{
    [Key]
    public int Id { get; set; }

    public int? RoleId { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string FullName { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PhoneNumber { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Address { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Username { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string PasswordHash { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string ProfilePictureUrl { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateOfBirth { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string CreatedBy { get; set; }

    public bool? IsDeleted { get; set; }
}