// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KoiCenter.WPF.Models;

[Table("Veterinarian")]
public partial class Veterinarian
{
    [Key]
    public int UserId { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Specialization { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string LicenseNumber { get; set; }

    public int? YearsOfExperience { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string ClinicAddress { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string ProfilePictureUrl { get; set; }

    [Column(TypeName = "decimal(3, 2)")]
    public decimal? Rating { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string CreatedBy { get; set; }

    public bool? IsDeleted { get; set; }
}