// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KoiCenter.WPF.Models;

[Table("VeterinarianAvailability")]
public partial class VeterinarianAvailability
{
    [Key]
    public int Id { get; set; }

    public int? VeterinarianId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? AvailableDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? AvailableFromTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? AvailableToTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string CreatedBy { get; set; }

    public bool? IsDeleted { get; set; }
}